//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIFR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string Id { get; set; }
        public string ManagerAccount { get; set; }
        public string ManagerPassword { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> LastVisitTime { get; set; }
        public string TestSiteCode { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
